BobRoss/config/routes.rb
Rails.application.routes.draw do
  resources :paintings
  resources :profiles
  get 'home/page'
  devise_for :users
  # devise_for :installs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # get '/', to:"home#page", "as:root" - same as below
  root 'home#page'

end

BobRoss/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

BobRoss/app/models/avatar.rb
class Avatar < ApplicationRecord
    has_many :avatars_profiles
    has_many :profiles, through: :avatars_profiles
end

BobRoss/app/models/avatars_profile.rb
class AvatarsProfile < ApplicationRecord
  belongs_to :avatar
  belongs_to :profile
end

BobRoss/app/models/colour.rb
class Colour < ApplicationRecord
    has_many :colours_paintings
    has_many :paintings, through: :colours_paintings
end

BobRoss/app/models/colours_painting.rb
class ColoursPainting < ApplicationRecord
  belongs_to :colour
  belongs_to :painting
end

BobRoss/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :painting
  belongs_to :profile
end

BobRoss/app/models/painting.rb
class Painting < ApplicationRecord
  belongs_to :profile
  has_many :colours_paintings
  has_many :colours, through: :colours_paintings
  has_one_attached :artwork
  validates_presence_of :season, :episode
  has_one :video, dependent: :destroy
end

BobRoss/app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :avatars_profiles
  has_many :avatars, through: :avatars_profiles
  has_many :paintings, dependent: :destroy
  has_many :artworks, dependent: :destroy
end

BobRoss/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :profile
end

BobRoss/app/models/video.rb
class Video < ApplicationRecord
  belongs_to :painting
end

BobRoss/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :authenticate_user!
end

BobRoss/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
    @painting = Painting.all
  end
end

BobRoss/app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_action :set_painting, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!

  # GET /paintings
  # GET /paintings.json
  def index
    @bob_arr = []
    @bob_arr = Profile.first.paintings.order(:season, :episode)
  end

  # GET /paintings/1
  # GET /paintings/1.json
  def show
    @paintall = Painting.all
  end

  # GET /paintings/new
  def new

    if current_user
      if current_user.profile
        @painting = Painting.new(river: false, waterfall: false, beach: false, mountains: false, cabin: false, animalguest: false, startcolour: "white", shape: "rectangle")
        @painting.save
      else
        redirect_to new_profile_path
      end
    else 
      redirect_to new_user_session_path
    end
  end

  # GET /paintings/1/edit
  def edit
  end

  # POST /paintings
  # POST /paintings.json
  def create
    @painting.artwork.attach(params[:painting][:artwork])
    @profile = Profile.new 
    @profile.id = current_user.profile.id #current_user = device and need to sign in
    @profile.save
    @painting.profile_id = @profile.id

    respond_to do |format|
      if @painting.save
        format.html { redirect_to @painting, notice: 'Painting was successfully created.' }
        format.json { render :show, status: :created, location: @painting }
      else
        format.html { render :new }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paintings/1
  # PATCH/PUT /paintings/1.json
  def update
    if @painting.artwork
      @painting.artwork.purge
    end
    # if @car.pictures
    #   @car.pictures.purge
    # end
    respond_to do |format|
      if @painting.update(painting_params)
        format.html { redirect_to @painting, notice: 'Painting was successfully updated.' }
        format.json { render :show, status: :ok, location: @painting }
      else
        format.html { render :edit }
        format.json { render json: @painting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paintings/1
  # DELETE /paintings/1.json
  def destroy
    @painting.destroy
    respond_to do |format|
      format.html { redirect_to paintings_url, notice: 'Painting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_painting
      @painting = Painting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def painting_params
      params.require(:painting).permit(:trees, :river, :cabin, :beach, :mountains, :waterfall, :guest, :animalguest, :startcolour, :shape, :likes, :artwork, :profile_id, :episode, :season, :other)
    end
end

BobRoss/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @painting = Painting.all
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    @user_type = params[:user_type] 
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    # @painting = Painting.new(painting_params) 
    # @painting.artwork.attach(params[:painting][:artwork])
    # @profile = Profile.new 
    # @profile.id = current_user.profile.id #current_user = device and need to sign in
    # @profile.save
    # @painting.profile_id = current_user.profile.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      puts"********************************************************"
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:username, :bio, :user_id)
    end
end

BobRoss/app/helpers/application_helper.rb
module ApplicationHelper
end

BobRoss/app/helpers/home_helper.rb
module HomeHelper
end

BobRoss/app/helpers/paintings_helper.rb
module PaintingsHelper
end

BobRoss/app/helpers/profiles_helper.rb
module ProfilesHelper
end

BobRoss/app/views/home/page.html.erb
<h1>A Happy Little Index</h1>
<h5>Enjoy the pictures uploaded by our Happy Little Bob Ross Community</h5>

<div class="row mt-5">
    <% if @painting.present? %>
        <% @painting.each do |painting| %>
            <div class="col-md-4 mt-5">
                <div class="card">
                    <% if painting.artwork.attached? %>
                        <%= image_tag painting.artwork, class: "card-img-top" %>
                    <% else %>
                        <%= image_tag "default.png" %>
                    <%end%>

                    <div class="card-body">
                        <h5 class="card-title btn btn-primary"><%= link_to "#{painting.profile.username}", profile_path(painting.profile.id), class: "btn btn-primary" %></h5>
                        <p class="card-text">Season: <%= painting.season %> Episode: <%= painting.episode %></p>
                        <%= link_to "Have a closer look", painting_path(painting.id), class: "btn btn-primary"%>
                    </div>
                </div>
            </div>
        <%end%>
    <%end%>
</div>

BobRoss/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BobRoss</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Barriecito|Poppins&display=swap" rel="stylesheet">
  </head>

  <body>
    <div class = "containers">
      <audio src="assets/bob_song.mp3" autoplay loop hidden>
        <p>Your browser does not support HTML5 audio playback</p>
      </audio>
      <%=render 'partials/navbar'%>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

BobRoss/app/views/paintings/_form.html.erb
<%= form_with(model: @painting, local: true) do |form| %>
  <% if @painting.errors.any? %>
    <div>
      <% pluralize(@painting.errors.count, "error") %>
      <% @painting.errors.full_messages.each do |message| %>
      <% end %>
    </div>
<% end %>

<div class="new_painting">
<% if current_user.id == 1 %>
  <div class="field">
    <%= form.label :river %>
    <%= form.check_box :river %>
  </div>

  <div class="field">
    <%= form.label :waterfall %>
    <%= form.check_box :waterfall %>
  </div>

  <div class="field">
    <%= form.label :beach %>
    <%= form.check_box :beach %>
  </div>
  
  <div class="field">
    <%= form.label :mountains %>
    <%= form.check_box :mountains %>
  </div>

  <div class="field">
    <%= form.label :cabin %>
    <%= form.check_box :cabin %>
  </div>

  <div class="field">
    <%= form.label :guest %>
    <%= form.text_field :guest %>
  </div>

  <div class="field">
    <%= form.label :animalguest, "Animal Guest" %>
    <%= form.check_box :animalguest %>
  </div>

  <div class="field">
    <%= form.label :startcolour, "Start Colour" %>
    <%= select_tag(:startcolour, options_for_select(['white', 'black', 'clear', 'acrylic black', 'grey', 'mixed', 'other'])) %>
  </div>

  <div class="field">
    <%= form.label :shape, "Canvas Shape" %>
    <%= select_tag(:shape, options_for_select([['rectangle', 1], ['oval', 2], ['other', 3]], 1)) %>
  </div>

  <div class="field">
    <%= form.label :other %>
    <%= form.text_field :other %>
  </div>

<% end %>

  <div class="field">
    <%= form.label :season %>
    <%= form.select :season, options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]), { prompt: 'Choose Season' } %>
  </div>

  <div class="field">
    <%= form.label :episode %>
    <%= form.select :episode, options_for_select([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]), { prompt: 'Choose Episode' } %>
  </div>

  <div class="field">
    <%= form.label :artwork %>
    <%= form.file_field :artwork %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

BobRoss/app/views/paintings/edit.html.erb
<h1>Editing Painting</h1>

<%= render 'form', artwork: @painting %>

<%= link_to 'Show', @painting %> |
<%= link_to 'Back', paintings_path %>

BobRoss/app/views/paintings/index.html.erb
<p id="notice"><%= notice %></p>

<div class = "row">
  <div class = "col-md-12">
    <div class = "row">
      <div class = "col-md-5">
        <h1>All Paintings by Bob Ross</h1>
        <h5>See what you like and click to follow along</h5>
      </div>

<!--Blue select-->
      <div >
<!-------------------- FIX THIS--------------------------------------------------------->
        <select id="season_search" class="mdb-select md-form colorful-select dropdown-primary" onchange="mysearch()"> 
<!-------------------- FIX THIS--------------------------------------------------------->
          <option selected="selected" value="all">All</option>
          <option value="1">Season 1</option>
          <option value="2">Season 2</option>
          <option value="3">Season 3</option>
          <option value="4">Season 4</option>
          <option value="5">Season 5</option>
          <option value="5">Season 7</option>
          <option value="5">Season 10</option>
          <option value="5">Season 12</option>
          <option value="5">Season 20</option>
        </select>
      </div>
      <label>Choose a season</label>
    </div>
  </div>
</div>

<div class = "row">
  <div class = "col-md-12">
    <div class = "row">
      <% @bob_arr.each do |bob| %>
        <div class="col-md-3 paintingEntry pictureSearch" data-season="<%=bob.season%>">
          <%= image_tag bob.artwork, class: "d-block w-100 shadow p-3 mb-3 bg-white rounded" %>
          <p> Bob Ross </p>
          <p>Season: <%= bob.season %> Episode: <%= bob.episode %></p>
          <%= link_to "Have a closer look", painting_path(bob.id), class: "btn btn-primary"%>
          <p>Likes: <%= bob.likes %></p>
          <br>
        </div>
      <% end %>
    </div>
  </div>
</div>
<br>
<%= link_to 'New Painting', new_painting_path %>

BobRoss/app/views/paintings/new.html.erb
<div class="new_form">
<h1>New Painting</h1>

<%= render 'form', picture: @painting %>

<%= link_to 'Back', paintings_path %>

</div>

BobRoss/app/views/paintings/show.html.erb
<div class="painting_show">
  <p id="notice"><%= notice %></p>
  <div class = "row justify-content-md-center">
    <div class = "col ml-5">
      <% if @painting.artwork %>
        <%= image_tag  @painting.artwork  if @painting.artwork.attached? %>
      <%end%>
    </div>
    
    <div class = "col mt-5">
      <% if @painting.river %>
        <p><strong>River</strong></p>
      <% end %>

      <% if @painting.beach %>
        <p><strong>Beach</strong></p>
      <% end %>

      <% if @painting.cabin %>
        <p><strong>Cabin</strong></p>
      <% end %>

      <% if @painting.waterfall %>
        <p><strong>Waterfall</strong></p>
      <% end %>

      <% if @painting.guest %>
        <p><strong>Guest:</strong><%= @painting.guest %></p>  
      <% end %>

      <% if @painting.animalguest %>
        <p><strong>Animal Guest</strong></p>
      <% end %>

      <p>
        <strong>Start Colour:</strong>
        <%= @painting.startcolour %>
      </p>

      <p>
        <strong>Start Shape:</strong>
        <%= @painting.shape %>
      </p>

      <p>
        <strong>Likes:</strong>
        <%= @painting.likes %>
      </p>

      <% if @painting.other %>
        <p><strong>Other:</strong></p>
      <% end %>
      
      <p>
        <strong>Season:</strong>
        <%= @painting.season %>
      </p>

      <p>
        <strong>Episode:</strong>
        <%= @painting.episode %>
      </p>

      <p>
        <strong>Creator:</strong>
        <%= @painting.profile.username %>
      </p>
    </div>

    <div class = "col d-flex align-items-center mr-5">
      <% if @painting.profile.user_id == 1 %>
        <iframe width="400" height="250" src="<%= @painting.video.address %>" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <% end %>
    </div>
  </div>

  <div class = "col-md-12">
    <div class = "row mt-5 peoples">
      <% if @painting.profile_id == 1 %>
        <% @paintall.each do |paint| %>
          <% if @painting.season == paint.season && @painting.episode == paint.episode %>
            <div class="col-md-3 user_pics">
              <%= image_tag paint.artwork, class: "d-block w-100 shadow p-3 mb-3 bg-white rounded" %>
              <%= paint.profile.username %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  
  <br>
  <% if user_signed_in? %>
    <% if current_user.id == @painting.profile.id %>
      <%= link_to 'Edit', edit_painting_path(@painting) %> |
    <% end %>
  <% end %>
  <a href="javascript:history.back()">Back</a>
</div>

BobRoss/app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="/">A Happy Little Index</a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path, class: "nav- btn btn-primary"%>
      </li>
     
      <li class="nav-item active">
        <%= link_to "Index", paintings_path, class: "nav- btn btn-primary"%>
      </li>

      <% if user_signed_in? %>
      <li class="nav-item active"> 
        <%= link_to "Upload my painting", new_painting_path, class: "nav- btn btn-primary"%>
      </li>

        <li class="nav-item active">
          <%= link_to "My Profile", profile_path(current_user.id), class: "nav- btn btn-primary"%>
        </li>
        
        <li class="nav-item">
          <%= link_to "LogOut", destroy_user_session_path, method: :delete, class: "nav-link"%>
        </li>
      <%else%>
        <li class="nav-item active">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav- btn btn-primary"%>
        </li>
        <%= link_to "LogIn", new_user_session_path(user_type:"returning_user"), class: "nav-link"%>
      </li>
      <%end%>
    </ul>
  </div>
</nav>

BobRoss/app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
      <ul>
        <% profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>
 
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

BobRoss/app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

BobRoss/app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Bio</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.username %></td>
        <td><%= profile.bio %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

BobRoss/app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

BobRoss/app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @profile.username %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @profile.bio %>
</p>

<p>
  <strong>Paintings:</strong>
  <div class = "row">
    <div class = "col-md-12">
      <div class = "row">
        <% @painting.each do |paintwork| %>
          <% if paintwork.profile_id.to_i == @profile.id.to_i %>
          <div class="col-md-3">
            <% if paintwork.artwork.attached? %>
            
                            <!-- Button trigger modal -->
              <button type="button" class="btn popart" data-toggle="modal" data-target="#exampleModalCenter<%= "#{paintwork.id}" %>"%>
                <%= image_tag paintwork.artwork, class: "d-block w-100 shadow p-3 mb-3 bg-white rounded" %>
              </button>

              <!-- Modal -->
              
              <div class="modal fade" id="exampleModalCenter<%= "#{paintwork.id}" %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
              
                <div class="modal-dialog modal-dialog-centered" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <h5 class="modal-title" id="exampleModalLongTitle">Season: <%= paintwork.season %> Episode: <%= paintwork.episode %></h5>
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    </div>
                    <div class="modal-body">
                      <%= image_tag paintwork.artwork, class: "d-block w-100 shadow p-3 mb-3 bg-white rounded" %>
                    </div>
                    <div class="modal-footer">
                      <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                  </div>
                </div>
              </div>

              <%#= image_tag paintwork.artwork, class: "d-block w-100 shadow p-3 mb-5 bg-white rounded" %>
            <% else %>
              <%= image_tag "default.png", class: "d-block w-100" %>
            <% end %>
          </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

<% if user_signed_in? %>
  <% if current_user.id == @profile.id %>
    <%= link_to 'Edit', edit_profile_path(@profile) %> |
  <% end %>
<% end %>
<a href="javascript:history.back()">Back</a>